### PR TITLE
Add new JEC uncertainty files

### PR DESCRIPTION
**Pull request by pastika**

### CODE REVIEW

**Comment by zhenbinwu** [comment]
Is other files also up to date?

**Comment by pastika** [comment]
What "other" files are you referring to?

**Comment by zhenbinwu** [comment]
The ones are already in the NanoAOD-tools. Some time they could be outdated and need a newer version of JEC from JME. Have you double checked we got them?

Also, the JEC uncertainty is fixed to the JEC we used in the NanoSUSY production I think. I guess you double checked as well.

**Comment by pastika** [comment]
@scarletnorberg confirmed that we are following the latest recommendations from the JEC twiki.  These  files I uploaded correspond to this recommendation.  I have no idea what the files that already exist in this repo are, but they are not what we should be using.

**Comment by zhenbinwu** [comment]
OK, merging then

**Pull request merged**
